# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17e5ce0235ed0f56e69e43be9b5109b6a5db4c712d62555142787d8865ef214b3d8e25c208e24cf2cbb236a520ffc3dc43cca4aa33b25865039c87068a94925c

test:
  secret_key_base: 693e9d5a8d14d427058da4c8e9239220294e032c93d109a00b55995bed2e0a6a32f01963d6417880b63c2e965e22070953bffe257ded1fd4e13aca76fb5ca713

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
